<?php

namespace Yana\Io\Adapters;

/**
 * @ignore
 */
require_once __DIR__ . '/../../../../include.php';

/**
 * Test class for ArrayAdapter.
 * Generated by PHPUnit on 2012-04-19 at 06:23:46.
 *
 * @package  test
 */
class ArrayAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ArrayAdapter
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new \Yana\Io\Adapters\ArrayAdapter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testUpdate()
    {
        $this->assertEquals(0, count($this->_object));
        $mockObject = new \Yana\Io\Adapters\MockSplSubject();
        $this->_object->update($mockObject);
        $this->assertEquals(1, count($this->_object));
        $this->assertEquals($mockObject, $this->_object[0]);
    }

    /**
     * @test
     */
    public function testGetIds()
    {
        $this->_object[1] = 0;
        $this->_object[2] = 0;
        $this->_object[3] = 0;
        $this->assertEquals(array(1, 2, 3), $this->_object->getIds());
    }

}

/**
 * Dummy class for mocking.
 *
 * @package test
 * @ignore
 */
class MockSplSubject implements \SplSubject
{

    public function attach(SplObserver $observer)
    {
        // intentionally left blank
    }

    public function detach(SplObserver $observer)
    {
        // intentionally left blank
    }

    public function notify()
    {
        // intentionally left blank
    }

}

?>