<?php
/**
 * PHPUnit test-case
 *
 * Software:  Yana PHP-Framework
 * Version:   {VERSION} - {DATE}
 * License:   GNU GPL  http://www.gnu.org/licenses/
 *
 * This program: can be redistributed and/or modified under the
 * terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 * This notice MAY NOT be removed.
 *
 * @package  test
 * @license  http://www.gnu.org/licenses/gpl.txt
 */

namespace Yana\Data\Adapters;

/**
 * @ignore
 */
require_once __DIR__ . '/../../../../include.php';

/**
 * Test class for SessionAdapter.
 * Generated by PHPUnit on 2012-04-19 at 06:46:16.
 *
 * @package  test
 */
class SessionAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Yana\Data\Adapters\SessionAdapter
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SESSION[__CLASS__] = null;
        $this->_object = new \Yana\Data\Adapters\SessionAdapter(__CLASS__);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function test()
    {
        $this->_object->offsetSet(1, 1);
        $this->_object[2] = 2;
        $this->assertEquals(1, $_SESSION[__CLASS__][1]);
        $this->assertEquals(2, $_SESSION[__CLASS__][2]);
        $this->assertEquals(count($_SESSION[__CLASS__]), count($this->_object));
        $_SESSION[__CLASS__][0] = 0;
        $this->assertEquals(0, $_SESSION[__CLASS__][0]);
    }

}

?>
