<GROUP_ID>
	<BLOCKED>
		<GROUP_NAME>{lang id="GROUPS.0"}</GROUP_NAME>
	</BLOCKED>
	<GUEST>
		<GROUP_NAME>{lang id="GROUPS.1"}</GROUP_NAME>
	</GUEST>
	<REGISTERED>
		<GROUP_NAME>{lang id="GROUPS.5"}</GROUP_NAME>
	</REGISTERED>
	<MOD>
		<GROUP_NAME>{lang id="GROUPS.2"}</GROUP_NAME>
	</MOD>
	<OWNER>
		<GROUP_NAME>{lang id="GROUPS.3"}</GROUP_NAME>
	</OWNER>
	<ADMIN>
		<GROUP_NAME>{lang id="GROUPS.4"}</GROUP_NAME>
	</ADMIN>
	<BLOG>
		<GROUP_NAME>blog</GROUP_NAME>
	</BLOG>
	<CALENDAR>
		<GROUP_NAME>calendar</GROUP_NAME>
	</CALENDAR>
	<DEFAULT>
		<GROUP_NAME>default</GROUP_NAME>
	</DEFAULT>
	<BAR>
		<GROUP_NAME>bar</GROUP_NAME>
	</BAR>
	<FOOBAR>
		<GROUP_NAME>foobar</GROUP_NAME>
	</FOOBAR>
	<GUESTBOOK>
		<GROUP_NAME>guestbook</GROUP_NAME>
	</GUESTBOOK>
	<MEDIADB>
		<GROUP_NAME>mediadb</GROUP_NAME>
	</MEDIADB>
	<PROJECT>
		<GROUP_NAME>project</GROUP_NAME>
	</PROJECT>
</GROUP_ID>
