<?php

namespace Yana\Views\Managers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-25 at 11:19:52.
 */
class RegistrationExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Yana\Views\Managers\RegistrationException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Yana\Views\Managers\RegistrationException();
    }

    /**
     * @test
     */
    public function testException()
    {
        $this->assertTrue($this->object instanceof \Yana\Views\Managers\RegistrationException);
    }

}
