<?php

namespace Yana\Views\Managers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-25 at 11:19:53.
 */
class ViewManagerExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Yana\Views\Managers\ViewManagerException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Yana\Views\Managers\ViewManagerException();
    }

    /**
     * @test
     */
    public function testException()
    {
        $this->assertTrue($this->object instanceof \Yana\Views\Managers\ViewManagerException);
    }

}
