<?php

namespace Yana\Templates\Helpers\Formatters;

use \Yana\Util\String;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../../templates/helpers/formatters/dateformatter.php';

/**
 * Test class for DateFormatter.
 * Generated by PHPUnit on 2011-11-08 at 23:42:18.
 */
class DateFormatterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @test
     */
    public function testInvoke()
    {
        $time = strtotime('2000-01-01 0:0:0');
        $dateFormatter = new DateFormatter();
        $string = $dateFormatter($time);
        $this->assertTrue(String::contains($string, 'new Date(' . $time . '000)'), 'Must contain JavaScript portion');
        $this->assertTrue(String::contains($string, date('r', $time)), 'Must contain PHP fallback');
    }

    /**
     * @test
     */
    public function testSetFormat()
    {
        DateFormatter::setFormat('c', 'date.toLocaleTimeString()');
        $time = strtotime('2000-01-01 0:0:0');
        $dateFormatter = new DateFormatter();
        $string = $dateFormatter($time);
        $this->assertTrue(String::contains($string, 'date.toLocaleTimeString()'), 'Must contain JavaScript value');
        $this->assertTrue(String::contains($string, date('c', $time)), 'Must contain PHP formatted value');
    }

}

?>
