<?php
$LANGUAGE += array
(
'language' => array(
    'de' => 'Sprache',
    'en' => 'Language'),
'english' => array(
    'de' => 'view this page in English'),
'german' => array(
    'de' => 'diese Seite auf Deutsch zeigen'),
'title' => array(
    'de' => 'Installationsprogramm',
    'en' => 'Installation Wizard'),
'welcome' => array(
    'de' => 'Herzlich willkommen',
    'en' => 'welcome'),
'navigation' => array(
    'de' => 'Navigation',
    'en' => 'navigation'),
'previous' => array(
    'de' => 'zur&uuml;ck',
    'en' => 'previous'),
'next' => array(
    'de' => 'weiter',
    'en' => 'next'),
'abort' => array(
    'de' => 'Installation abbrechen',
    'en' => 'abort installation'),
'license_link' => array(
    'de' => 'Den Text der Lizenz können Sie hier einsehen',
    'en' => 'You can view the license text here'),
'publisher_link' => array(
    'de' => 'Webseite des Herstellers',
    'en' => 'publisher\'s website'),
'software_uses' => array(
    'de' => 'Diese Software benutzt',
    'en' => 'This software uses the'),
'author' => array(
    'de' => 'Autor',
    'en' => 'author'),
'proceed' => array(
    'de' => 'Fortfahren',
    'en' => 'proceed'),
'license_proceed' => array(
    'de' => 'Um mit der Installation zu beginnen, müssen Sie die Lizenzbedingungen lesen und erklären, dass Sie akzeptieren, an diese Bedingungen gebunden zu sein.',
    'en' => 'To begin the installation, you need to read the license agreement and accept to be bound to the restrictions defined therein.'),
'license_accept' => array(
    'de' => 'Ich habe die Lizenzbedingungen gelesen und akzeptiert',
    'en' => 'I have read and accepted the license agreement'),
'license_reject' => array(
    'de' => 'Ich akzeptiere die Lizenzbedingungen nicht',
    'en' => 'I do not accept the license agreement'),
'license_rejected' => array(
    'de' => 'Ohne gültige Lizenz kann die Installation leider nicht fortgesetzt werden.',
    'en' => 'Without a valid license the installation can not continue.'),
'pass_too_short' => array(
    'de' => 'Das Passwort muss mindestens 8 Zeichen lang sein. Versuchen Sie es erneut.',
    'en' => 'The passwords need to be at least 8 characters long. Please try again.'),
'pass_miss' => array(
    'de' => 'Die eingegebenen Passwörter stimmen nicht überein. Versuchen Sie es erneut.',
    'en' => 'The two entered passwords do not match. Please try again.'),
'license' => array(
    'de' => 'Ihre Lizenz',
    'en' => 'Your license'),
'license_info' => array(
    'de' => "Um das Produkt nutzen zu können, müssen Sie die folgenden Lizenzbedingungen akzeptieren.\n\nBitte scrollen Sie bis zum Ende der Seite.",
    'en' => "To be able to use the product you must accept the following license agreements.\n\nPlease scroll on to the end of the page."),
'php_self' => array(
    'de' => $_SERVER['PHP_SELF']),
'components' => array(
    'de' => 'Komponenten zur Installation auswählen',
    'en' => 'choose components to install'),
'choose_all' => array(
    'de' => 'Volle Installation',
    'en' => 'full installation'),
'choose_minimal' => array(
    'de' => 'Minimale Installation',
    'en' => 'minimal installation'),
'choose_typical' => array(
    'de' => 'Typische Installation',
    'en' => 'typical installation'),
'installation' => array(
    'de' => 'Installation',
    'en' => 'installation'),
'install_info' => array(
    'de' => 'Klicken Sie auf die Schaltfläche um mit der Installation zu beginnen.',
    'en' => 'Click the button to start the installation.'),
'install_start' => array(
    'de' => 'Installation jetzt starten',
    'en' => 'start installation now'),
'install_complete' => array(
    'de' => 'Installation abgeschlossen',
    'en' => 'installation complete'),
'install_complete_info' => array(
    'de' => 'Die Installation ist nun abgeschlossen. Vielen Dank!',
    'en' => 'The installation is now complete. Thank you!'),
'install_success' => array(
    'de' => 'Komponenten wurden erfolgreich entpackt',
    'en' => 'components unpacked successfully'),
'install_failure' => array(
    'de' => 'Entpacken der Komponenten gescheitert!',
    'en' => 'Failure while unpacking components!'),
'pass' => array(
    'de' => 'Passwort für Administrator festlegen',
    'en' => 'Set password for administrator'),
'pass_info' => array(
    'de' => 'Bitte geben Sie ein Passwort ein und bestätigen Sie mit Klick auf OK.',
    'en' => 'Please enter a password and click on OK.'),
'pass1' => array(
    'de' => 'Passwort',
    'en' => 'password'),
'pass2' => array(
    'de' => 'Passwort wiederholen',
    'en' => 'repeat password'),
'pass_hint' => array(
    'de' => 'Empfehlungen f&uuml;r sichere Passwörter',
    'en' => 'Suggestions for secure passwords'),
'pass_text' => array(
    'de' => 'Das Passwort sollte nicht leicht zu erraten sein. Geburtstage, Namen von Personen und alle Begriffe, die man in Duden oder Wörterbüchern findet, sind denkbar ungeeignet.
        Es sollte mehr als 8 Zeichen lang sein und mindestens 1 Großbuchstaben, 1 Zahl und 1 Sonderzeichen enthalten, jedoch möglichst nicht am Anfang oder Ende des Wortes.

        Dass man sich "gute Passwörter" so schlecht merken könne, ist nicht korrekt.
        Ein einfaches Beispiel: "n8sleuchtenMond&amp;*e" (nachts leuchten Mond und Sterne)

        Alternativ können Sie auch einen Satz überlegen, welcher leicht zu merken ist und die Anfangsbuchstaben der Worte als Passwort verwenden.
        Zum Beispiel: "meine Oma fährt 1 rote Harley mit 180 Km / Stunde nach Berlin" als Passwort "mOf1rHm180K/SnB".',
    'en' => 'The password should\'nt be easy to guess. Birthdates, names and words from dictionaries are not well suited.
        It should be at least 8 characters long and should contain at least 1 capital letter, 1 number and 1 special char.
        
        Good passwords need not to be difficult to remember.
        E.g.: "@n8moon&amp;*sshinebr8" (at night moon and stars shine bright)
        
        Also you may imagine a sentence and take the first letter of the words as the password.
        E.g.: "my Granny drives 1 red Harley at 100 Miles / Hour to London" as password "mGd1rHa100M/HtL"'),
'test' => array(
    'de' => 'Installation auf Fehler prüfen',
    'en' => 'Check installation for errors'),
'test_details' => array(
    'de' => 'Setzen Sie einen Haken bei &quot;{language more_details}&quot;, wenn Sie eine detailierte Aufschlüsselung wünschen.',
    'en' => 'Check the box &quot;{language more_details}&quot; to get a detailed list.'),
'test_info' => array(
    'de' => 'Bitte klicken Sie auf OK um mit der Prüfung zu beginnen.',
    'en' => 'Please click OK to begin the check.'),
'more_details' => array(
    'de' => 'mehr Details',
    'en' => 'more details'),
'run_application' => array(
    'de' => 'Die Anwendung jetzt starten.',
    'en' => 'Run the application now.'),
'finish' => array(
    'de' => 'Fertigstellen',
    'en' => 'finish'),
);
?>
