<FOOID>
    <1>
            <FOOID>1</FOOID>
            <FVALUE>28</FVALUE>
            <FNUMBER>1</FNUMBER>
    </1>
    <2>
            <FOOID>2</FOOID>
            <FVALUE>44</FVALUE>
            <FNUMBER>3</FNUMBER>
    </2>
    <3>
            <FOOID>3</FOOID>
            <FVALUE>12</FVALUE>
            <FNUMBER>6</FNUMBER>
    </3>
</FOOID>