<?php

namespace Yana\Util\Xml;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-23 at 17:15:52.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Collection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Collection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $this->object->offsetSet(null, "1");
        $this->assertEquals(new \Yana\Util\Xml\Object("1"), $this->object->offsetGet(0));
    }

    /**
     * @test
     * @expectedException \Yana\Core\Exceptions\InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        $this->object->offsetSet(null, new \Yana\Core\Object());
    }

}
