<?php
/**
 * YANA library
 *
 * Software:  Yana PHP-Framework
 * Version:   {VERSION} - {DATE}
 * License:   GNU GPL  http://www.gnu.org/licenses/
 *
 * This program: can be redistributed and/or modified under the
 * terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 * This notice MAY NOT be removed.
 *
 * @package  yana
 * @license  http://www.gnu.org/licenses/gpl.txt
 */

namespace Yana\Core\Dependencies;

/**
 * @ignore
 */
require_once __DIR__ . '/../../../../include.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-31 at 22:56:56.
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $configurationFactory = new \Yana\ConfigurationFactory();
        $configuration = $configurationFactory->loadConfiguration(YANA_INSTALL_DIR . 'config/system.config.xml');
        $this->object = new \Yana\Core\Dependencies\Container($configuration);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testGetRequest()
    {
        $this->assertTrue($this->object->getRequest() instanceof \Yana\Http\Facade);
    }

    /**
     * @test
     */
    public function testGetCache()
    {
        $this->assertTrue($this->object->getCache() instanceof \Yana\Data\Adapters\IsDataAdapter);
    }

    /**
     * @test
     * @todo   Implement testGetExceptionLogger().
     */
    public function testGetExceptionLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertTrue($this->object->getExceptionLogger() instanceof \Yana\Log\IsLogger);
    }

    /**
     * @test
     */
    public function testGetSecurity()
    {
        $this->assertTrue($this->object->getSecurity() instanceof \Yana\Security\IsFacade);
    }

    /**
     * @test
     */
    public function testGetRegistry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertTrue($this->object->getRegistry() instanceof \Yana\VDrive\IsRegistry);
    }

    /**
     * @test
     */
    public function testGetPlugins()
    {
        $this->assertTrue($this->object->getPlugins() instanceof \Yana\Plugins\Manager);
    }

    /**
     * @test
     * @todo   Implement testGetView().
     */
    public function testGetView()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertTrue($this->object->getView() instanceof \Yana\Views\Managers\IsManager);
    }

    /**
     * @test
     */
    public function testGetLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertTrue($this->object->getLanguage() instanceof \Yana\Translations\Facade);
    }

    /**
     * @test
     */
    public function testGetSkin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertTrue($this->object->getSkin() instanceof \Yana\Views\Skins\IsSkin);
    }

    /**
     * @test
     */
    public function testGetId()
    {
        $this->assertTrue(is_string($this->object->getProfileId()));
    }

    /**
     * @test
     */
    public function testGetLogger()
    {
        $this->assertTrue($this->object->getLogger() instanceof \Yana\Log\IsLogHandler);
    }

}
