<GROUP_ID>
	<TESTGROUP>
		<GROUP_NAME>TEST</GROUP_NAME>
	</TESTGROUP>
	<TEST2>
		<GROUP_NAME>TEST2</GROUP_NAME>
	</TEST2>
	<ADMIN>
		<GROUP_NAME>{lang id="GROUPS.4"}</GROUP_NAME>
	</ADMIN>
</GROUP_ID>
