<?php

namespace \Yana\Forms\Setups;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for FormSetupCacheManager.
 * Generated by PHPUnit on 2011-04-11 at 20:41:55.
 */
class CacheManagerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FormSetupCacheManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Yana\Forms\Setups\CacheManager();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSet()
    {
        $formSetup = new \Yana\Forms\Setup();
        $this->assertFalse(isset($this->object->test));
        $this->object->test = $formSetup;
        $this->assertTrue(isset($this->object->test));
        $result = $this->object->test;
        $this->assertEquals($formSetup, $result);
        unset($this->object->test);
        $this->assertFalse(isset($this->object->test));
    }

}

?>