<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../ddlfieldcollection.php';

/**
 * Test class for DDLFieldCollection.
 * Generated by PHPUnit on 2011-03-24 at 23:18:35.
 */
class DDLFieldCollectionTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var DDLFieldCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DDLFieldCollection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $o = new DDLField('name');
        $this->object['test'] = $o;
        $this->assertTrue($this->object['test'] instanceof DDLField, 'Instance was not added.');
        $this->assertEquals($this->object['test']->getName(), $o->getName());
    }

    /**
     * @test
     */
    public function testOffsetSetAutodetect()
    {
        $o = new DDLField('name');
        $this->object[] = $o;
        $this->assertTrue($this->object['name'] instanceof DDLField, 'Instance was not added.');
        $this->assertEquals($this->object['name']->getName(), $o->getName());
    }

    /**
     * @test
     * @expectedException \Yana\Core\Exceptions\InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        $this->object[] = new Object();
    }

}

?>