<?php

namespace Yana\Forms\Fields;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for FormFieldFacadeCollection.
 * Generated by PHPUnit on 2011-04-21 at 01:05:50.
 */
class FacadeCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FormFieldFacadeCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FacadeCollection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $wrapper = new \Yana\Forms\ContextSensitiveWrapper(new \Yana\Forms\Facade(), new \Yana\Forms\Setups\Context('test'));
        $item = new Facade($wrapper, new \Yana\Db\Ddl\Column('test'), new \Yana\Db\Ddl\Field('test'));
        $this->object['test'] = $item;
        $this->assertEquals($item, $this->object['test']);
    }

    /**
     * @test
     * @expectedException \Yana\Core\Exceptions\InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        $this->object->offsetSet('test', 'invalid value');
    }

}

?>