<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for FieldCollection.
 * Generated by PHPUnit on 2011-03-24 at 23:18:35.
 */
class FieldCollectionTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var \Yana\Db\Ddl\FieldCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Yana\Db\Ddl\FieldCollection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $o = new \Yana\Db\Ddl\Field('name');
        $this->object['test'] = $o;
        $this->assertTrue($this->object['test'] instanceof \Yana\Db\Ddl\Field, 'Instance was not added.');
        $this->assertEquals($this->object['test']->getName(), $o->getName());
    }

    /**
     * @test
     */
    public function testOffsetSetAutodetect()
    {
        $o = new \Yana\Db\Ddl\Field('name');
        $this->object[] = $o;
        $this->assertTrue($this->object['name'] instanceof \Yana\Db\Ddl\Field, 'Instance was not added.');
        $this->assertEquals($this->object['name']->getName(), $o->getName());
    }

    /**
     * @test
     * @expectedException \Yana\Core\Exceptions\InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        $this->object[] = new \Yana\Core\Object();
    }

}

?>