<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../fieldwarning.php';

/**
 * Test class for InvalidFieldWarning.
 * Generated by PHPUnit on 2011-03-29 at 19:07:07.
 */
class InvalidFieldWarningTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidFieldWarning
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FieldWarning();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSetField()
    {
        $this->object->setField('field');
        $this->assertEquals(array('FIELD' => 'field'), $this->object->getData());
    }

}

?>