<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../filesizeerror.class.php';

/**
 * Test class for FilesizeError.
 * Generated by PHPUnit on 2011-03-29 at 18:36:40.
 */
class FilesizeErrorTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var FilesizeError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FilesizeError;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSetFilename()
    {
        $this->assertEquals(array('FILE' => 'test'), $this->object->setFilename('test')->getData());
    }

    /**
     * @test
     */
    public function testSetMaxSize()
    {
        $this->assertEquals(array('MAXIMUM' => '123'), $this->object->setMaxSize('123')->getData());
    }

    /**
     * @test
     */
    public function testSetBoth()
    {
        $data = array('FILE' => 'test', 'MAXIMUM' => '123');
        $this->object->setFilename('test')->setMaxSize('123');
        $this->assertEquals($data, $this->object->getData());
    }

}

?>
