<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../uploadfailederror.php';

/**
 * Test class for UploadFailedError.
 * Generated by PHPUnit on 2011-03-29 at 18:39:39.
 */
class UploadFailedErrorTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var UploadFailedError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileError();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSetFilename()
    {
        $this->assertEquals(array('FILE' => 'test'), $this->object->setFilename('test')->getData());
    }

}

?>
