<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../formsetupcontext.class.php';

/**
 * Test class for FormSetupContext.
 * Generated by PHPUnit on 2011-04-14 at 02:14:23.
 */
class FormSetupContextTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var FormSetupContext
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormSetupContext('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @test
     */
    public function testGetName()
    {
        $this->assertEquals('test', $this->object->getName());
    }

    /**
     * @test
     */
    public function testGetRows()
    {
        $this->assertTrue($this->object->getRows() instanceof FormRowIterator, 'Instance of FormRowIterator expected.');
    }

    /**
     * @test
     */
    public function testUpdateRow()
    {
        $newValues = array('b' => array('a' => 2), 'c' => array('d' => array(1, 2, 3)));
        $oldValues = array('a' => 1, 'c' => array('d' => ''));
        $this->object->updateRow(1, $oldValues);
        $this->object->updateRow(1, $newValues);
        $row = $this->object->getRows()->offsetGet(1);
        $this->assertEquals($oldValues['a'], $row['a']);
        $this->assertEquals($newValues['b'], $row['b']);
        $this->assertEquals($newValues['c'], $row['c']);
    }

    /**
     * @test
     */
    public function testGetValue()
    {
        $this->assertEquals(null, $this->object->getValue('test'));
    }

    /**
     * @test
     */
    public function testGetValues()
    {
        $this->assertEquals(array(), $this->object->getValues());
    }

    /**
     * @test
     */
    public function testSetValue()
    {
        $values = array('a' => 1, 'b' => array('a' => 2), 'c' => array('d' => array(1, 2, 3)));
        $this->object->setValues($values);
        $this->assertEquals($values['a'], $this->object->getValue('a'));
        $this->assertEquals($values['b'], $this->object->getValue('b'));
        $this->assertEquals($values['b']['a'], $this->object->getValue('b.a'));
        $this->assertEquals($values['c'], $this->object->getValue('c'));
        $this->assertEquals($values['c']['d'], $this->object->getValue('c.d'));
        $this->assertEquals(1, $this->object->getValue('c.d.0'));
    }

    /**
     * @test
     */
    public function testSetValues()
    {
        $values = array(1, 2, 3);
        $this->assertEquals($values, $this->object->setValues($values)->getValues());
    }

    /**
     * @test
     */
    public function testAddValues()
    {
        $newValues = array('b' => array('a' => 2), 'c' => array('d' => array(1, 2, 3)));
        $oldValues = array('a' => 1, 'c' => array('d' => ''));
        $this->object->setValues($oldValues);
        $this->object->addValues($newValues);
        $this->assertEquals($oldValues['a'], $this->object->getValue('a'));
        $this->assertEquals($newValues['b'], $this->object->getValue('b'));
        $this->assertEquals($newValues['b']['a'], $this->object->getValue('b.a'));
        $this->assertEquals($newValues['c'], $this->object->getValue('c'));
        $this->assertEquals($newValues['c']['d'], $this->object->getValue('c.d'));
        $this->assertEquals(1, $this->object->getValue('c.d.0'));
    }

    /**
     * @test
     */
    public function testSetAction()
    {
        $this->assertEquals('functionName', $this->object->setAction('functionName')->getAction());
    }

    /**
     * @test
     */
    public function testGetAction()
    {
        $this->assertEquals('', $this->object->getAction());
    }

    /**
     * @test
     */
    public function testGetColumnNames()
    {
        $this->assertEquals(array(), $this->object->getColumnNames());
    }

    /**
     * @test
     */
    public function testSetColumnNames()
    {
        $columnNames = array('a', 'B', 'Ä');
        $this->assertEquals($columnNames, $this->object->setColumnNames($columnNames)->getColumnNames());
    }

}

?>