<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../formfieldfacadecollection.class.php';

/**
 * Test class for FormFieldFacadeCollection.
 * Generated by PHPUnit on 2011-04-21 at 01:05:50.
 */
class FormFieldFacadeCollectionTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var FormFieldFacadeCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormFieldFacadeCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $item = new FormFieldFacade(new FormFacade(), new DDLColumn('test'), new FormSetupContext('test'));
        $this->object['test'] = $item;
        $this->assertEquals($item, $this->object['test']);
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}

?>