<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../invalidcharacterwarning.php';

/**
 * Test class for InvalidCharacterWarning.
 * Generated by PHPUnit on 2011-03-06 at 22:08:58.
 */
class InvalidCharacterWarningTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidCharacterWarning
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InvalidCharacterWarning();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSetField()
    {
        $this->object->setField('field');
        $this->assertEquals(array('FIELD' => 'field'), $this->object->getData());
    }

    /**
     * @test
     */
    public function testSetValue()
    {
        $this->object->setValue('value');
        $this->assertEquals(array('VALUE' => 'value'), $this->object->getData());
    }

    /**
     * @test
     */
    public function testSetValid()
    {
        $this->object->setValid('a-z');
        $this->assertEquals(array('VALID' => 'a-z'), $this->object->getData());
    }

}

?>