<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../invalidactionerror.class.php';

/**
 * Test class for InvalidActionError.
 * Generated by PHPUnit on 2011-03-29 at 18:28:15.
 */
class InvalidActionErrorTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidActionError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InvalidActionError();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testSetAction()
    {
        $this->assertEquals(array('ACTION' => 'test'), $this->object->setAction('test')->getData());
    }

}

?>
