<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../plugineventroute.class.php';

/**
 * Test class for PluginEventRoute.
 * Generated by PHPUnit on 2011-03-06 at 17:06:23.
 */
class PluginEventRouteTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var PluginEventRoute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PluginEventRoute();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testType()
    {
        $this->assertEquals(PluginEventRoute::CODE_SUCCESS, $this->object->getCode());
    }

    /**
     * @test
     */
    public function testSetCode()
    {
        $this->object->setCode(404);
        $this->assertEquals(404, $this->object->getCode());
    }

    /**
     * @test
     */
    public function testGetTarget()
    {
        $this->assertEquals('', $this->object->getTarget());
    }

    /**
     * @todo Implement testSetTarget().
     */
    public function testSetTarget()
    {
        $this->object->setTarget('test');
        $this->assertEquals('test', $this->object->getTarget());
    }

    /**
     * @test
     */
    public function testGetMessage()
    {
        $this->assertEquals('', $this->object->getMessage());
    }

    /**
     * @test
     */
    public function testSetMessage()
    {
        $this->object->setMessage(PluginEventRoute::MSG_SUCCESS);
        $this->assertEquals(PluginEventRoute::MSG_SUCCESS, $this->object->getMessage());
    }

}

?>