<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../pluginmenuentry.class.php';

/**
 * Test class for PluginMenuEntry.
 * Generated by PHPUnit on 2011-03-07 at 00:23:44.
 */
class PluginMenuEntryTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var PluginMenuEntry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PluginMenuEntry();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testGetGroup()
    {
        $this->assertEquals('', $this->object->getGroup());
    }

    /**
     * @test
     */
    public function testSetGroup()
    {
        $this->object->setGroup('foo.bar');
        $this->assertEquals('foo.bar', $this->object->getGroup());
    }

    /**
     * @test
     */
    public function testGetTitle()
    {
        $this->assertEquals('', $this->object->getTitle());
    }

    /**
     * @test
     */
    public function testSetTitle()
    {
        $this->object->setTitle('{lang id="foo"}');
        $this->assertEquals('{lang id="foo"}', $this->object->getTitle());
    }

    /**
     * @test
     */
    public function testGetIcon()
    {
        $this->assertEquals('', $this->object->getIcon());
    }

    /**
     * @test
     */
    public function testSetIcon()
    {
        $this->object->setIcon('foo');
        $this->assertEquals('foo', $this->object->getIcon());
    }

    /**
     * @test
     */
    public function testGetSafeMode()
    {
        $this->assertNull($this->object->getSafeMode());
    }

    /**
     * @test
     */
    public function testSetSafeMode()
    {
        $this->object->setSafeMode(true);
        $this->assertTrue($this->object->getSafeMode());
        $this->object->setSafeMode(false);
        $this->assertFalse($this->object->getSafeMode());
        $this->object->setSafeMode(null);
        $this->assertNull($this->object->getSafeMode());
    }

}

?>