<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../pluginannotationparser.php';

/**
 * Test class for PluginAnnotationParser.
 * Generated by PHPUnit on 2011-03-29 at 16:21:13.
 */
class PluginAnnotationParserTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var PluginAnnotationParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $text = '
            /**
             * Äöß.
             *
             * @access public
             * @param string $test1
             * @param array  $test2
             * {@test  Key1: Value, Key2: Value,
             *        Key3: Value}
             * @test2  Key1: Value, Key2: Value, Key3: Value
             */
        ';
        $this->object = new PluginAnnotationParser($text);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testGetText()
    {
        $object = new PluginAnnotationParser();
        $this->assertEquals('', $object->getText());
    }

    /**
     * @test
     */
    public function testSetText()
    {
        $text = "Test";
        $this->assertEquals($text, $this->object->setText($text)->getText());
    }

    /**
     * @test
     */
    public function testGetTag()
    {
        $this->assertEquals('public', $this->object->getTag('access'));
        $array = array(
            'Key1' => 'Value',
            'Key2' => 'Value',
            'Key3' => 'Value'
        );
        $this->assertEquals($array, $this->object->getTag('test'));
        $this->assertEquals($array, $this->object->getTag('test2'));
    }

    /**
     * @test
     */
    public function testGetTags()
    {
        $array = array(
            'string $test1',
            'array  $test2'
        );
        $this->assertEquals($array, $this->object->getTags('param'));
    }

}

?>
