<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../pluginmethodcollection.php';

/**
 * Test class for PluginMethodCollection.
 * Generated by PHPUnit on 2011-03-23 at 02:56:43.
 */
class PluginMethodCollectionTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var PluginClassCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PluginMethodCollection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @test
     */
    public function testOffsetSet()
    {
        $o = new PluginConfigurationMethod();
        $o->setMethodName('methodName');
        $this->object['test'] = $o;
        $this->assertTrue($this->object['test'] instanceof PluginConfigurationMethod, 'Instance was not added.');
        $this->assertEquals($this->object['test']->getMethodName(), $o->getMethodName());
    }

    /**
     * @test
     */
    public function testOffsetUnset()
    {
        $o = new PluginConfigurationMethod();
        $o->setMethodName('methodName');
        $this->object['test'] = $o;
        $this->assertTrue($this->object['test'] instanceof PluginConfigurationMethod, 'Instance was not added.');
        unset($this->object['test']);
        $this->assertTrue($this->object['test'] === null, 'Instance was not unset.');
    }

    /**
     * @test
     */
    public function testOffsetSetAutodetect()
    {
        $o = new PluginConfigurationMethod();
        $o->setMethodName('methodName');
        $this->object[] = $o;
        $this->assertTrue($this->object['methodname'] instanceof PluginConfigurationMethod, 'Instance was not added.');
        $this->assertEquals($this->object['methodname']->getMethodName(), $o->getMethodName());
    }

    /**
     * @test
     * @expectedException \Yana\Core\Exceptions\InvalidArgumentException
     */
    public function testOffsetSetInvalidArgumentException()
    {
        $this->object[] = "invalid value";
    }

}

?>