<?php

namespace Yana\Views;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-25 at 11:19:53.
 */
class ViewExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Yana\Views\ViewException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Yana\Views\ViewException();
    }

    /**
     * @test
     */
    public function testException()
    {
        $this->assertTrue($this->object instanceof \Yana\Views\ViewException);
    }

}
