<?php
/**
 * YANA library
 *
 * Software:  Yana PHP-Framework
 * Version:   {VERSION} - {DATE}
 * License:   GNU GPL  http://www.gnu.org/licenses/
 *
 * This program: can be redistributed and/or modified under the
 * terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 * This notice MAY NOT be removed.
 *
 * @package  yana
 * @license  http://www.gnu.org/licenses/gpl.txt
 */

namespace Yana\Core\Exceptions;

/**
 * @ignore
 */
require_once __DIR__ . '/../../../../include.php';

/**
 * Test class for ResultTypeEnumeration.
 * Generated by PHPUnit on 2012-08-09 at 19:36:04.
 */
class ResultTypeEnumerationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @test
     */
    public function testValues()
    {
        $this->assertEquals('alert', \Yana\Core\Exceptions\ResultTypeEnumeration::ALERT);
        $this->assertEquals('error', \Yana\Core\Exceptions\ResultTypeEnumeration::ERROR);
        $this->assertEquals('message', \Yana\Core\Exceptions\ResultTypeEnumeration::MESSAGE);
        $this->assertEquals('warning', \Yana\Core\Exceptions\ResultTypeEnumeration::WARNING);
    }

}

?>
